{
 "title": "risingwave_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "barrier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "barrier_survival_time > 0.1s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "barrier_survival_time_sum/1000000 > 0.1",
     "legendFormat": "barrier_last_epoch = {{barrier_last_epoch}}"
    }
   ]
  },
  {
   "title": "actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "actor throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(stream_actor_row_count[15s])",
       "legendFormat": "actor_id = {{actor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "source throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "rows/s" }
     ],
     "targets": [
      {
       "expr": "rate(stream_source_output_rows_counts[15s])",
       "legendFormat": "source_id = {{source_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "hummock_get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "get_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_get_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_get_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_get_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "sum(rate(state_store_get_latency_sum[5m])) / sum(rate(state_store_get_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "get_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_get_counts[1m])) by (type)",
       "legendFormat": "get_count"
      }
     ]
    },
    {
     "title": "get_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(state_store_get_key_size_sum)/sum(state_store_get_key_size_count)",
       "legendFormat": "get_key_size"
      },
      {
       "expr": "sum(state_store_get_value_size_sum)/sum(state_store_get_value_size_count)",
       "legendFormat": "get_value_size"
      }
     ]
    },
    {
     "title": "get_snapshot_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_get_snapshot_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(state_store_get_snapshot_latency_bucket[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_get_snapshot_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_get_snapshot_latency_sum[5m])) / sum(rate(state_store_get_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "hummock_write_batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "write_batch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_batched_write_counts[1m])) by (type)",
       "legendFormat": "get_count"
      }
     ]
    },
    {
     "title": "write_batch_kv_pair_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_batched_write_tuple_counts[1m])) by (type)",
       "legendFormat": "get_count"
      }
     ]
    },
    {
     "title": "write_batch_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_batched_write_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_batched_write_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batched_write_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_batched_write_latency_sum[5m])) / sum(rate(state_store_batched_write_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "add_l0_sst_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_batch_write_add_l0_ssts_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_batch_write_add_l0_ssts_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batch_write_add_l0_ssts_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_batch_write_add_l0_ssts_latency_sum[5m])) / sum(rate(state_store_batch_write_add_l0_ssts_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "build_table_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_batch_write_build_table_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_batch_write_build_table_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batch_write_build_table_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_batch_write_build_table_latency_sum[5m])) / sum(rate(state_store_batch_write_build_table_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "write_batch_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(state_store_batched_write_size_sum)/sum(state_store_batched_write_size_count)",
       "legendFormat": "get_key_size"
      }
     ]
    }
   ]
  },
  {
   "title": "hummock_iter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "iter_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_iter_counts[1m])) ",
       "legendFormat": "get_count"
      }
     ]
    },
    {
     "title": "iter_next_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_iter_next_counts[1m])) ",
       "legendFormat": "get_count"
      }
     ]
    },
    {
     "title": "iter_next_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_iter_next_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_next_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_next_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_iter_next_latency_sum[5m])) / sum(rate(state_store_iter_next_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "iter_seek_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_iter_seek_latency_bucket[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_seek_latency_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_seek_latency_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(rate(state_store_iter_seek_latency_sum[5m])) / sum(rate(state_store_iter_seek_latency_count[5m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "hummock_summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(state_store_get_key_size_sum)/sum(state_store_get_key_size_count)",
       "legendFormat": "get_key_size"
      },
      {
       "expr": "sum(state_store_get_value_size_sum)/sum(state_store_get_value_size_count)",
       "legendFormat": "get_value_size"
      },
      {
       "expr": "sum(state_store_batched_write_size_sum)/sum(state_store_batched_write_size_count)",
       "legendFormat": "batch_write_size"
      }
     ]
    },
    {
     "title": "count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(state_store_get_counts[1m])) ",
       "legendFormat": "get_count"
      },
      {
       "expr": "sum(rate(state_store_batched_write_counts[1m])) ",
       "legendFormat": "batched_write_count"
      },
      {
       "expr": "sum(rate(state_store_batched_write_tuple_counts[1m])) ",
       "legendFormat": "batched_write_kv_pair_count"
      },
      {
       "expr": "sum(rate(state_store_iter_next_counts[1m])) ",
       "legendFormat": "iter_next_count"
      },
      {
       "expr": "sum(rate(state_store_iter_counts[1m])) ",
       "legendFormat": "iter_count"
      }
     ]
    },
    {
     "title": "p99_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_get_latency_bucket[5m])) by (le))",
       "legendFormat": "get_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_get_snapshot_latency_bucket[5m])) by (le))",
       "legendFormat": "get_snapshot_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_next_latency_bucket[5m])) by (le))",
       "legendFormat": "iter_next_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_seek_latency_bucket[5m])) by (le))",
       "legendFormat": "iter_seek_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batched_write_latency_bucket[5m])) by (le))",
       "legendFormat": "batched_write_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batch_write_build_table_latency_bucket[5m])) by (le))",
       "legendFormat": "batch_write_build_table_latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_batch_write_add_l0_ssts_latency_bucket[5m])) by (le))",
       "legendFormat": "batch_write_add_l0_ssts_latency"
      }
     ]
    }
   ]
  }
 ]
}